services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    network_mode: host

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      
    ports:
      - "3000:3000"
    environment:
      - SERVER_URL=http://backend:8000